import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "../components/Sidebar";
import { ThemeProvider } from "../components/ThemeProvider";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      {/* <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}> */}
      <body className={`${inter.className} flex h-screen overflow-hidden`}>
        <ThemeProvider>
          {/* Sidebar Component */}
          <Sidebar />

          {/* Area Konten Utama */}
          <main className="flex-1 flex flex-col h-screen overflow-y-auto">
            {/* Top Navbar ringan & dinamis */}
            <header className="h-20 bg-white/80 dark:bg-[#020817]/80 backdrop-blur-md border-b border-slate-200 dark:border-slate-800 flex items-center justify-between px-8 sticky top-0 z-40 transition-colors duration-700">
              <h1 className="text-xl font-semibold text-slate-800 dark:text-slate-100 transition-colors duration-700">Overview</h1>

              {/* Profil Pengguna */}
              <div className="flex items-center gap-3">
                <div className="text-right hidden md:block">
                  <p className="text-sm font-medium text-slate-700 dark:text-slate-300 transition-colors duration-700">Administrator</p>
                  <p className="text-xs text-slate-500 dark:text-slate-400 transition-colors duration-700">Divisi Sistem Informasi</p>
                </div>
                <div className="h-10 w-10 rounded-full bg-teal-600 flex items-center justify-center text-white font-bold shadow-sm">
                  A
                </div>
              </div>
            </header>

            {/* Tempat halaman dirender */}
            <div className="p-8">
              {children}
            </div>
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
